// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function PelotaPlaya(props) {
//   const { nodes, materials } = useGLTF('/pelota.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[2.996, 0.539, -2.965]} scale={0.312}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['13517_Beach_Ball_v2_L3_1'].geometry}
//           material={materials.Beach_Ball_transparent_plastic}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes['13517_Beach_Ball_v2_L3_2'].geometry}
//           material={materials.Beach_Ball_rubber}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/pelota.glb')



import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"
import { RigidBody } from '@react-three/rapier';

export function PelotaPlayaLineal(props) {
  const pelotaRef = useRef(null)
  const pelotaBodyRef = useRef(null)

  const { nodes, materials } = useGLTF('/assets/models/pelotaPlaya/pelota.glb')
  const speed = 9

  useFrame((state, delta) => {
    const currentPosition = pelotaBodyRef.current?.translation()

    let moveX = currentPosition?.x
    let moveY = currentPosition?.y

    if (currentPosition?.x >= -3.5 && currentPosition?.x < 5 && currentPosition?.y == 0) {
      moveX += delta * speed;
    }
    else if (currentPosition?.x > 5 && currentPosition?.y >= 5) {
      moveX -= delta * speed;
      moveY += delta * speed;
    }
    else if (currentPosition?.x > -5 && currentPosition?.y >= 0.0) {
      moveX -= delta * speed;
      moveY -= delta * speed;
    }
    else {
      moveX = 0.0;
      moveY = 0.0;
    }

    pelotaBodyRef.current?.setTranslation({
      x:  moveX,
      y:  moveY,
      z:  pelotaBodyRef.current?.translation().z
    }, true)
  })

  return (
    <RigidBody ref={pelotaBodyRef} type="fixed" position={props.position}>
      <group ref={pelotaRef} {...props} dispose={null}>
        {/* <group rotation={[2.996, 0.539, -2.965]} scale={0.312}> */}
        <group rotation={[2, 0, 2]} scale={0.03}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['13517_Beach_Ball_v2_L3_1'].geometry}
            material={materials.Beach_Ball_transparent_plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['13517_Beach_Ball_v2_L3_2'].geometry}
            material={materials.Beach_Ball_rubber}
          />
        </group>
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/assets/models/pelotaPlaya/pelota.glb')